### PR TITLE
Added Screenshot And Firefox Support

### PR DESCRIPTION
**Pull request by htho**
Hello Bradley,

thank you for creating this provider.

I needed some more functions so I did some extensios and changes.

* Screenshot support
* Firefox support
* I had to restructure the code to allow multiple browsers while staying readable.
* I added JSDoc comments and type information.

Unfortunately there is [a problem with TestCafe](https://github.com/DevExpress/testcafe/issues/2918) so Screenshots from Firefox don't work yet.

I am looking forward to improve this provider with you.

### CODE REVIEW

**Comment by htho** [comment]
Hi @bsmithb2 I can see that you already updated the npm package. Do you plan to merge this PR, or is something wrong with it?

**Comment by htho** [comment]
btw. TestCafe is fixed now, so that Firefox should run fine.

**Comment by bsmithb2** [comment]
sorry - was on my honeymoon - happy to share merge rights with you if you wish so you can help maintain?

**Comment by htho** [comment]
no problem - congratulations

I am happy to help out, although I am busy right now.

**Pull request merged**
